### ISSUE TITLE
Add support for Jira URL from RapidBoard

### ISSUE THREAD

**Issue by nicysneiros** [labcodes/harvest-jira#2]
When we start "Harvest Time Tracking" from the Agile Board modal, the permalink saved in the Harvest is in a different format than expected in the script (see screenshot)
![screen shot 2019-02-18 at 11 49 34](https://user-images.githubusercontent.com/3246075/52959183-611ca180-3374-11e9-9ad9-006a0c98fddc.png)

**Comment by luizbraga** [comment]
@nicysneiros Should we close this issue?
